language: php

php:
  - 7.1
env:
  matrix:
    -
    - DEPENDENCIES=--prefer-lowest

cache:
  directories:
    - .composer/cache

matrix:
  fast_finish: true

before_install:
  - alias composer=composer\ --no-interaction && composer selfupdate
  - composer global require hirak/prestissimo

install:
  - travis_retry composer update --no-progress --profile --no-scripts --no-suggest $DEPENDENCIES

script:
   - vendor/bin/grumphp run
